### PR TITLE
first working draft

### PR DESCRIPTION
**Pull request by mcwhittemore**
@rclark 👀 

Partial failures would screw up the metadata with how this code is written right now. I need to think about how to get the value of bulk processing without creating this problem. I think there might be something to be done with filtering edits by metadata updated times... tbd.

### CODE REVIEW

**Comment by rclark** [comment]
Could you clarify your concern here? Partial failure? 

We've always known that applying the same feature edit to the metadata record more than once would negatively impact the metadata. Rather than try to accommodate all the edge cases, I had always thought it would just be easier to routinely update the metadata doc by rereading the entire dataset.

**Comment by mcwhittemore** [comment]
Yea, I think you might be right. My fear is that if the table this is being written to rejects one right, all the records will be reprocessed. I don't really want to write a `re-metadata` function as that would require bringing in `cardboard-list`. I think we can be good with this problem for now.

**Comment by rclark** [comment]
I'm not sure I share your fear of cross-module dependency. Library-per-index will encourage isolation and solid API that will lead to better, more testable code -- even if in the end we just merge all the libraries back into a single module, which we can always do if we feel like it.

**Comment by mcwhittemore** [comment]
Yea, the further I get into this the less cross cardboard dependency bothers me.

Each of the sub-index modules might want/need a 'setup' function that can be run one time to create the index for a single dataset or all datasets. This won't be required if you index all the features from the start, but if you add an index later on it would be good to have a defined way to get going.

**Comment by mcwhittemore** [comment]
Any code concerns here?

**Review by rclark — COMMENTED** [review]
My only comment here is similar to https://github.com/mapbox/cardboard-list/pull/1#discussion_r90495969

I think that there is reason to consider wrapping stream-handler functionality into cardboard(-main). The concept would be that these index libraries should not need to be able to parse the details of the actual dynamodb records, because that creates an implicit dependency without a real API contract.

**Pull request merged**
